modLoader = "javafml"
loaderVersion = "[1,)"
#issueTrackerURL = ""
license = "0BSD"

[[mods]]
modId = "emojiless"
version = "${version}"
displayName = "Emojiless"
authors = "Skye"
description = '''
Super simple emoji rendering based on Inline
'''
logoFile = "icon.png"

[[mixins]]
config = "emojiless.mixins.json"

[[dependencies.emojiless]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.emojiless]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.emojiless]]
modId = "inline"
type = "required"
versionRange = "*"
ordering = "NONE"
side = "BOTH"
